Repository SRE-PRG/azmitool, pull requests merged in 2020-10, with the labels that each got.

#193 Update NuGet packages
  src/azmi-main/azmi-main.csproj
  test/azmi-commandline-tests/azmi-commandline-tests.csproj
Labels: maintenance

#203 Logger
  src/azmi-commandline/azmi-commandline.cs
  src/azmi-commandline/azmi-commandline.csproj
  src/azmi-commandline/nlog.config
  src/azmi-main/azmi-main.csproj
  src/azmi-main/blob/GetBlob.cs
  src/azmi-main/blob/GetBlobs.cs
  src/azmi-main/blob/ListBlobs.cs
  src/azmi-main/blob/SetBlob.cs
  src/azmi-main/blob/SetBlobs.cs
  src/azmi-main/certificate/GetCertificate.cs
  src/azmi-main/common/GetToken.cs
  src/azmi-main/secret/GetSecret.cs
Labels: hacktoberfest-accepted

#204 Abs path
  src/azmi-main/blob/ListBlobs.cs
  test/integration/blob-tests.sh
Labels: hacktoberfest-accepted

#207 Update Commands.md
  Commands.md
Labels: hacktoberfest-accepted

#217 Default .NET editorconfig file + formatting
  .editorconfig
  azmi.sln
  src/azmi-commandline/AzmiCommandLineExtensions.cs
  src/azmi-commandline/azmi-commandline.cs
  src/azmi-main/AzmiArgument.cs
  src/azmi-main/AzmiException.cs
  src/azmi-main/blob/GetBlob.cs
  src/azmi-main/blob/GetBlobs.cs
  src/azmi-main/blob/ListBlobs.cs
  src/azmi-main/blob/SetBlob.cs
  src/azmi-main/blob/SetBlobs.cs
  src/azmi-main/blob/interfaces/BlobClientImpl.cs
  src/azmi-main/blob/interfaces/ContainerClientImpl.cs
  src/azmi-main/blob/interfaces/IBlobClient.cs
  src/azmi-main/blob/interfaces/IContainerClient.cs
  src/azmi-main/certificate/GetCertificate.cs
  src/azmi-main/common/GetToken.cs
  src/azmi-main/secret/GetSecret.cs
  test/azmi-commandline-tests/Extensions-Tests.cs
  test/azmi-commandline-tests/azmi-commandline-tests.cs
Labels: hacktoberfest-accepted

#210 Different
  src/azmi-main/blob/SetBlobs.cs
  test/integration/blob-tests.sh
  test/performance/3-multiple-blobs-tests.sh
Labels: hacktoberfest-accepted

#218 --skip-if-same documentation update
  Commands.md
  Examples.md
Labels: hacktoberfest-accepted

#213 added condition before creating directory in getblobs
  src/azmi-main/blob/GetBlobs.cs
Labels: Storage, bug
